all: districts_113 districts_116_pa legislators

districts_113:
	python ../scripts/build_districts_census.py --start 113 --end 115

districts_116_pa:
	python ../scripts/build_districts_116_pa.py

legislators:
	python ../scripts/build_legislators.py
